package errors

import "errors"

var (
	UserConflict              = errors.New("Lỗi: người dùng đã tồn tại")
	SignUpFail                = errors.New("Đăng kí thất bại")
	SignInFail                = errors.New("Đăng nhập thất bại")
	UserNotFound              = errors.New("Email này chưa được đăng kí")
	UserNotUpdated            = errors.New("Cập nhật không thành công")
	UserNotDeleted            = errors.New("Xoá không thành công")
	NotAdmin                  = errors.New("Không phải quyền Admin")
	NotUsers                  = errors.New("Không phải quyền Users")
	UserAddressNotFound       = errors.New("User không có tồn tại")
	AddAddressFail            = errors.New("Thêm địa chỉ thất bại")
	DefaultAddressFail        = errors.New("Đặt địa chỉ mặc định thất bại")
	AddMenuItemsFail          = errors.New("Thêm menu items thất bại")
	EditMenuItemsFail         = errors.New("Sửa menu items thất bại")
	ItemIDNotFound            = errors.New("Item không tồn tại")
	DeleteMenuItemsFail       = errors.New("Xoá menu items thất bại")
	AddDiscountFail           = errors.New("Thêm Mã giảm giá thất bại")
	DiscountCodeConflict      = errors.New("Mã giảm giá đã tồn tại")
	DiscountCodeIDNotFound    = errors.New("Mã giảm giá không tồn tại")
	EditDiscountFail          = errors.New("Sửa mã giảm giá thất bại")
	DeleteDiscountFail        = errors.New("Xoá mã giảm giá thất bại")
	AddOrderItemsFail         = errors.New("Thêm order items thất bại")
	AddOrderFail              = errors.New("Thêm order thất bại")
	AddPaymentFail            = errors.New("Thêm payment thất bại")
	AddOrderDiscountsFail     = errors.New("Thêm order discounts thất bại")
	AddHistoryTransactionFail = errors.New("Thêm lịch sử giao dịch thất bại")
	StatusOrderFail           = errors.New("Cập nhật trạng thái đơn hàng thất bại")
	HistoryOrderFail          = errors.New("Lịch sử đơn hàng thất bại")
	OrderNotFound             = errors.New("Đơn hàng không tồn tại")
	AddFeedbackFail           = errors.New("Thêm feedback thất bại")
	FeedbackNotFound          = errors.New("Feedback không tìm thấy")
	//GetMenuItemsFail          = errors.New("Lấy menu items thất bại")
)
